### ISSUE TITLE
swagger-ui as submodule

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-api#2]
I thought we could exclude swagger-ui from the repo, and still use it through a submodule reference. Perhaps some bash script would be required for configuration, otherwise :pizza:

**Comment by jasiek-net** [comment]
I can install `swagger-ui` via `package.json` and copy `swagger-ui/dist/` from `node_modules` to our server static files, I think that would be the easiest solution.

**Comment by michalmikolajczyk** [comment]
I was thinking git submodules though https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by michalmikolajczyk** [comment]
bump

**Comment by jasiek-net** [comment]
`swagger-ui` is a `npm package`, so there is no need to create git submodules if we can keep all dependencies in `package.json` and run all scripts via `npm script`

**Comment by michalmikolajczyk** [comment]
sounds good, as long as we don't have the swagger UI files tracked in our repo.
