### ISSUE TITLE
typos from PR

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-api#26]
please check comments in #25

**Comment by jasiek-net** [comment]
answered https://github.com/michalmikolajczyk/viking-garage-api/pull/25#discussion_r123874688

**Comment by michalmikolajczyk** [comment]
Answer to that comment:
Sequelize uses the `inflection` library https://github.com/dreamerslab/node.inflection to handle the grammar. Let's just add `accessory – accessories` as an exception, if needed.

**Comment by michalmikolajczyk** [comment]
bump

**Comment by jasiek-net** [comment]
done in #34

**Comment by michalmikolajczyk** [comment]
that PR has not been merged into `master`
