### ISSUE TITLE
where are the emails sent to?

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-api#28]
@jonzee
as an anonymous user
on https://www.vikinggarage.com
I choose an offer
and I click RIDE
fill the form
confirm
get confirmation screen
I did NOT get any email

I checked the env variables on `dev` and `prod` on Heroku, there are some differences. Please confirm that we are processing incoming messages.

**Comment by michalmikolajczyk** [comment]
this is still bugged. Now on production.

@jonzee please treat this bug as the top priority.

<img width="1680" alt="screen shot 2017-07-06 at 1 48 25 am" src="https://user-images.githubusercontent.com/1655227/27889573-70e55d1e-61ed-11e7-8401-5964987faabb.png">
<img width="1680" alt="screen shot 2017-07-06 at 1 48 09 am" src="https://user-images.githubusercontent.com/1655227/27889574-70e82490-61ed-11e7-8767-f0fce51f9422.png">

**Comment by jasiek-net** [comment]
issue doubled https://github.com/michalmikolajczyk/viking-garage-frontend/issues/106
