### ISSUE TITLE
Configure nodemailer with API key (not credentials)

### ISSUE THREAD

**Issue by jasiek-net** [michalmikolajczyk/viking-garage-api#29]

**Comment by jasiek-net** [comment]
done in #30

**Comment by michalmikolajczyk** [comment]
it does not work!

**Comment by jasiek-net** [comment]
checkout `.env.example` (in #30 and #33), you have to add env vars for gmail oauth2

**Comment by michalmikolajczyk** [comment]
- [x] use `app.json` to check for the required env vars in `env` file
- [x] add to README

**Comment by michalmikolajczyk** [comment]
covered by #38
