### ISSUE TITLE
cleanup README

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-api#3]
as per:
https://github.com/michalmikolajczyk/viking-garage-api/pull/1#discussion_r102609059

**Comment by michalmikolajczyk** [comment]
bump

**Comment by jasiek-net** [comment]
Ok, I moved `config` description to `src/config.ts.example`

**Comment by michalmikolajczyk** [comment]
sounds good, let's make a PR, then close this task. The PR should really just handle this simple change.
