### ISSUE TITLE
Please check for cloudinary plan & limits

### ISSUE THREAD

**Issue by jasiek-net** [michalmikolajczyk/viking-garage-api#36]
We had cloudinary installed on `api-dev`, I installed cloudinary on `api-production`, copied all photos there and created `pr` https://github.com/michalmikolajczyk/viking-garage-frontend/pull/125 with photos url to `api-production`.
We used about 50% of bandwidth plan limit on `api-dev` already.

**Comment by michalmikolajczyk** [comment]
@jonzee please configure Cloudinary dev on all our environments, including the review apps.

**Comment by jasiek-net** [comment]
@michalmikolajczyk ok, and upload photos to every environment?

**Comment by michalmikolajczyk** [comment]
it's not really necessary just for reading, but for writing, it will be. The images should be pruned on test environments.

**Comment by jasiek-net** [comment]
@michalmikolajczyk ok, I added cloudinary to all api environments
