### ISSUE TITLE
Prepare flow for database migration, tests & backups

### ISSUE THREAD

**Issue by jasiek-net** [michalmikolajczyk/viking-garage-api#37]

**Comment by michalmikolajczyk** [comment]
- [x] baza danych produkcyjna - backup w dwóch miejscach (follower + Github LFS)
- [ ] testy bazy danych - obciążeniowe (HammerDB, pgbench, TPC – info)
- [ ] testy aplikacji przy błędzie bazy danych (sprawdzić na dev)
- [ ] testowa baza danych - aktualizowana razem z oprogramowaniem (aktualny plik `.json` + opis w `README.md`, ewentualnie drugi plik `README_DB.md`)
- [x] trzeba znaleźć odpowiednie narzędzie
- [x] doprecyzować co my robimy! prawidłowa nazwa procesu który robimy
- [x] heroku - system przechowywania danych efemeryczny (przy resecie dyno dane znikają)
- [x] trzy etapy migracji: sprawdzamy bazową, potem w środowisku drugim, a potem dopiero wrzucamy na production-live
---
- [ ] można z poziomu node sprawdzać bazę danych
- [ ] aplikacja ma dostęp do swojego systemu plików (porównanie jaka wersja bazy danych jest aktualnie i jaka jest obsługiwana przez aplikację)
- [ ] travis mógłby to obsługiwać

**Comment by michalmikolajczyk** [comment]
- [ ] sprawdzamy akutalna baze danych
- [ ] jesli nie ma - budujemy nowa w oparciu o schemat
- [ ] jesli jest i nie zgadzaja sie wersje to robimy migracje
- [ ] wersja bazy danych nie moze byc wyzsza od tagu (tag moze byc wyzszy od bazy danych)
- [ ] gdy sprawdzamy ze jest 1.1, a w migracji jest 15 kolejnych to rozpoczynamy skrypty migracji po kolei
- [ ] po wykonaniu wszystkich skryptow (help check po miedzy kolejnymi migracjami)
- [ ] w migrations powinnismy dopisywac wiecej informacji
- [ ] potem wczytywac sobie nie tylko wersje ale ile danych spodziewamy sie usunac
- [ ] robimy na koncu help check i to tyle!
- [ ] musimy zrobic review aps dla API beda robiły pierwsz test bazy danych
- [ ] review aps przy tworzeniu robia kopie bazy danych staging i probuja zmigrowac baze danych do nowej wersji (ale na swojej bazie danych a nie na staging - tworza swoja baze danych)
- [ ] kolejny krok to zbudowanie aplikacji na staging
- [ ] musimy miec endpoint helpcheck ktory sprawdza czy wszystko jest ok z baza danych - to sprawdzamy recznie (open app, wchodzimy na url /helpcheck)
- [ ] jesli to jest ok to zatwierdzamy aplikacje (czyli merge do master)
- [ ] i potrzebujemy jeszcze jedno srodowisko - qa - quality assurance pomiedzy dev a staging; tylko qa sie aktualizuje na master
- [ ] qa jest tylko po to zeby z frontend przetestowac api; wchodzimy na frontend-qa zeby sprawdzic czy dziala api-qa; z frontend-qa robimy testy end-to-end
- [ ] aktualizujemy staging
- [ ] aktualizujemy produkcja (fragile); dwie aplikacje produkcyjne i aktualizacja jednej - jesli jedna sie wywala to podmieniamy pod druga

- [ ] musimy robic migracje na kopi bazy danych
- [ ] na produkcji jest o wiele wiecej danych; 
- [ ] mozemy miec skrypty ktore przy samym qa sprawdzaja ilosc danych na produkcji i automatycznie generuja taka sama ilosc danych (np. 15 razy wrzucaja taki sam blad) i probuja robic migracje przy takiej samej liczbie danych

**Comment by michalmikolajczyk** [comment]
flow migracji jest zmienione, obsługiwane w ramach hostingu
