### ISSUE TITLE
cleanup unrelated files, also cleanup comments

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-api#4]
e.g.
https://github.com/michalmikolajczyk/viking-garage-api/pull/1#discussion_r102612407
https://github.com/michalmikolajczyk/viking-garage-api/pull/1#discussion_r102612738

**Comment by michalmikolajczyk** [comment]
bump

**Comment by jasiek-net** [comment]
fixed

**Comment by michalmikolajczyk** [comment]
cool, will close the task when the changes are merged into `master` via a PR

**Comment by jasiek-net** [comment]
done in #6
